### ISSUE TITLE
Incompatibilty with gunicorn.

### ISSUE THREAD

**Issue by AJamesPhillips** [logentries/le_python#3]
We have a web app using django and gunicorn, I don't appreciate how gunicorn handles its workers but after [the recent changes](https://github.com/logentries/le_python/commit/c39b4002ec865dfb94622810ad4aaf71a9871906) we're getting:  

```
2013-10-08 12:28:31 [ERROR] gunicorn.error: Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 55, in handle
    self.handle_error(req, client, addr, e)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 177, in handle_error
    self.log.exception("Error handling request")
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gunicorn/glogging.py", line 219, in exception
    self.error_log.exception(msg, *args)
  File "/usr/lib/python2.7/logging/__init__.py", line 1172, in exception
    self.error(msg, exc_info=1, *args)
  File "/usr/lib/python2.7/logging/__init__.py", line 1166, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1258, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1268, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1308, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 748, in handle
    self.emit(record)
  File "/home/ubuntu/venv/src/logentries/logentries/utils.py", line 122, in emit
    self._thread.start()
  File "/usr/lib/python2.7/threading.py", line 488, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
```

If there's any further information I can provide that might help please let me know, also apologies if this is not an issue for le_python, however when we moved to commit `1726b2271b0fa6d9da4332e165f4ae394e4ffd47` it seems to have resolved the problem.  We're using gunicorn 18.0, python 2.7, ubuntu, and we're monkey patching gunicorn.  `from gevent import monkey; monkey.patch_all(subprocess=False)`

**Comment by StephenHynes7** [comment]
Can you try the latest version ? https://pypi.python.org/pypi/Logentries

**Comment by yrunts** [comment]
Error is reproducible when running workers using Celery.

**Comment by rsaftoiu** [comment]
Seeing the same issue with Logentries==0.7, Django==1.4.20, django-celery==3.1.10:

Traceback (most recent call last):
  File "/home/fedora/deploy/master/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/fedora/deploy/master/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/fedora/deploy/master/webapp/shopventoryapp/common/tasks.py", line 110, in run
    result, exception =  self.do_timed_work(*args, **kwargs)
  File "/home/fedora/deploy/master/webapp/shopventoryapp/common/tasks.py", line 132, in do_timed_work
    kwargs))
  File "/usr/lib64/python2.7/logging/__init__.py", line 1182, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1175, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1268, in _log
    self.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1278, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1318, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/home/fedora/deploy/master/lib/python2.7/site-packages/logentries/utils.py", line 184, in emit
    self._thread.start()
  File "/usr/lib64/python2.7/threading.py", line 740, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once

**Comment by hihell** [comment]
same issue with logentries 0.7 and flask

**Comment by drgarcia1986** [comment]
Same here with logentries 0.14 + aiohttp + gunicorn

**Comment by drgarcia1986** [comment]
To solve this issue I had to make a `pass` on the exception
```diff
             except RuntimeError: # It's already started.
-                if not self._thread.is_alive():
-                    raise
+                pass
```

**Comment by chrisguidry** [comment]
Likewise here, just using `multiprocessing` in Python 2.7 and the logentries 0.15 Python client.

**Comment by Sandeep4** [comment]
Same problem with multiple processes in python.

**Comment by Sandeep4** [comment]
Does not happen it we don't use logging in the parent process.

**Comment by advance512** [comment]
We had the same issue using 0.15.

Problem was that we called:

```
import gevent
import gevent.monkey
gevent.monkey.patch_all()
```

after calling the Logentries handler.
This happened in a bastardized piece of code, that was a mix of several other projects.. and so this happened.

Interestingly, it didn't happen on the dev machine, but it did in a cloud env. 

Not sure why.

**Comment by drgarcia1986** [comment]
Maybe the PR #46 solve this issue
