### ISSUE TITLE
Getting error while installing linux agent

### ISSUE THREAD

**Issue by hussainanjar** [logentries/le_python#37]
I'm getting following error while installing linux agent

```bash
***** Step 2 of 3 - Login *****
Traceback (most recent call last):
  File "/usr/bin/le", line 8, in ?
    sys.exit(
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 236, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 2097, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 1830, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/share/logentries/logentries/le.py", line 2375
    return resp['host'] if resp['response'] == 'ok' else None
                         ^
SyntaxError: invalid syntax
```

**Comment by hussainanjar** [comment]
I need to upgrade python.
