### ISSUE TITLE
logger thread dies when exception contains illegal characters.

### ISSUE THREAD

**Issue by jtheuer** [logentries/le_python#49]
We found this exception during testing:

```
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/local/lib/python2.7/dist-packages/logentries/utils.py", line 96, in run
multiline = le_helpers.create_unicode(data).replace(
File "/usr/local/lib/python2.7/dist-packages/logentries/helpers.py", line 31, in create_unicode
return unicode(ch, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf5 in position 716: invalid start byte
```

```
> python --version
Python 2.7.6
```

Since the worker thread dies, the whole application will suddenly stop working because of https://github.com/logentries/le_python/issues/48

**Comment by jtheuer** [comment]
From my logs, root cause could have been:
```
2016-02-04 15:20:32 pid=8 ERROR Ignored error handling exif for reorientation
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 158, in get_orientation
    segment = ExifSegment(None, None, self.exif, 'ro')
  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 856, in __init__
    DefaultSegment.__init__(self, marker, fd, data, mode)
  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 150, in __init__
    self.parse_data(data)
  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 866, in parse_data
    "expecting <Exif>" % exif)
InvalidSegment: Bad Exif Marker. Got <Exif�>, expecting <Exif>
```
Note the unprintable char behind <Exif

**Comment by vilda** [comment]
Fixed now via your MR, thanks for reporting!
